# Generated by Django 5.1.5 on 2025-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
