# Generated by Django 5.1.5 on 2025-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'UserGroup'}, related_name='user_groups', to='myapp.useroption'),
        ),
    ]
