# Generated by Django 5.1.5 on 2025-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_job_user_kind_alter_useroption_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroption',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'not active'), (1, 'active')], default=0),
        ),
    ]
