# Generated by Django 5.1.5 on 2025-01-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_useroption'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useroption',
            table='myapp_user_options',
        ),
    ]
